#!/bin/bash

installer="./installer" && [[ ! -d ${installer} ]] && mkdir ${installer}

msg () {
    BRAN='\033[1;37m' && VERMELHO='\e[31m' && VERDE='\e[32m' && AMARELO='\e[33m'
    AZUL='\e[34m' && MAGENTA='\e[35m' && MAG='\033[1;36m' &&NEGRITO='\e[1m' && SEMCOR='\e[0m'
    case $1 in
        -ne)cor="${VERMELHO}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}";;
        -ama)cor="${AMARELO}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
        -verm)cor="${AMARELO}${NEGRITO}[!] ${VERMELHO}" && echo -e "${cor}${2}${SEMCOR}";;
        -azu)cor="${MAG}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
        -verd)cor="${VERDE}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
        -bra)cor="${BRAN}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}";;
        "-bar2"|"-bar")cor="${AZUL}${NEGRITO}———————————————————————— ${2} ————————————————————————————" && echo -e "${SEMCOR}${cor}${SEMCOR}";;
    esac
}
export -f msg

if [[ "${EUID}" -ne 0 ]]; then
    msg -verm "Kamu harus jalankan script ini mode root"
    exit 1
fi

# Lakukan sudo su

aturFirewall () {
    msg -ama "Menghidupkan dan mengatur Firewall "
    a() { if [[ $@ = "" ]];then echo "halo"; else echo $@; fi; }
    
    if [[ $@ = "on" ]];then
        ufw enable -y &>/dev/null
        ufw allow ssh  &>/dev/null
        ufw allow http &>/dev/null
        ufw allow https &>/dev/null
        elif [[ $@ = "off" ]];then
        ufw disable -y &>/dev/null
        elif [[ $@ != "" ]];then
        IFS=' '
        for portt in "$@";do
            ufw allow $portt &>/dev/null
        done
    fi
}
export -f msg

installModule(){
    msg -bar "Tahap awal"
    msg -ama "Membuat module update"
    msg -ama "Untuk mempermudah user dalam mengupdate sistem"
    echo "sudo apt-get update&&sudo apt-get upgrade -y&&sudo apt-get dist-upgrade -y&&sudo apt-get autoremove -y" > /bin/update&&sudo chmod 777 /bin/update
    msg -ama "Silahkan ketik, 'update' untuk mengupdate sistem"
    [[ $(dpkg --get-selections|grep -w "curl"|head -1) ]] || (msg -ama "(1) Menginstall Module ..."&&apt-get install curl -y &>/dev/null&&tput cuu1 && tput dl1)
    [[ $(dpkg --get-selections|grep -w "wget"|head -1) ]] || (msg -ama "(2) Menginstall Module ..."&&apt-get install wget -y &>/dev/null&&tput cuu1 && tput dl1)
    [[ $(dpkg --get-selections|grep -w "git"|head -1) ]] || (msg -ama "(3) Menginstall Module ..."&&apt-get install git -y &>/dev/null&&tput cuu1 && tput dl1)
    [[ $(dpkg --get-selections|grep -w "apache2"|head -1) ]] || (msg -ama "(3) Menginstall Module ..."&&apt-get install apache2 -y &>/dev/null&&tput cuu1 && tput dl1)
    [[ $(dpkg --get-selections|grep -w "libc6"|head -1) ]] || (msg -ama "(3) Menginstall Module ..."&&apt-get install libc6 -y &>/dev/null&&tput cuu1 && tput dl1)
    [[ $(dpkg --get-selections|grep -w "nginx-full"|head -1) ]] || (msg -ama "(3) Menginstall Module ..."&&apt-get install nginx-full -y &>/dev/null&&tput cuu1 && tput dl1)
    [[ $(dpkg --get-selections|grep -w "libstdc++6"|head -1) ]] || (msg -ama "(3) Menginstall Module ..."&&apt-get install libstdc++6 -y &>/dev/null&&tput cuu1 && tput dl1)
    [[ $(dpkg --get-selections|grep -w "ufw"|head -1) ]] || (msg -ama "(3) Menginstall Module ..."&&apt-get install ufw -y &>/dev/null&&tput cuu1 && tput dl1)
}

buatVariabel() {
    msg -bar "Pertanyaan"
    while [[ ${onfirewall} != @(s|S|y|Y|n|N) ]]; do
        read -p "$(msg -ama "Apakah anda ingin menghidupkan firewall? (Y/T): ")" onfirewall
        tput cuu1 && tput dl1
    done
    msg -ama "Firewall Hidup ? $onfirewall"
    if [[ onfirewall = @(s|S|y|Y) ]];then
        aturFirewall on
    fi
}
export -f buatVariabel

selection_fun () {
    local selection="null"
    local range
    for((i=0; i<=$1; i++)); do range[$i]="$i "; done
    while [[ ! $(echo ${range[*]}|grep -w "$selection") ]]; do
        echo -ne "\033[1;37mPilih opsi: " >&2
        read selection
        tput cuu1 >&2 && tput dl1 >&2
    done
    echo $selection
}
export -f selection_fun

float_data () {
    ofc="\033[0m${gren}(#OFC)"
    dev="\033[0m${gren}(#DEV)"
    bet="\033[0m${gren}(#BET)"
    case $1 in
        "code-server.sh")echo -ne "$(msg -verd "[$2]") $(msg -verm2 ">") " && msg -azu "Code Server";;
        *)echo -ne "$(msg -verd "[$2]") $(msg -verm2 ">") " && msg -azu "${1^^} \033[1;33m(Tanpa deskripsi!)";;
    esac
}

##################################################################
# cd /opt&&sudo chmod -R 755 ./&&sudo wget https://nodejs.org/download/release/latest/node-v17.3.1-linux-x64.tar.gz &>/dev/null&&sudo tar -xvf node-* &>/dev/null
# echo """# NodeJS
# export NODEJS_HOME=/opt/node-v14.14.0-linux-x64/bin
# export PATH=\$NODEJS_HOME:\$PATH""" >>/etc/bash.bashrc&&. /etc/bash.bashrc

installModule
buatVariabel

tooll () {
    msg -bar "Menu Alat"
    script[0]="Kembali"
    local Numb=1
    for arqs in $(ls ${installer}); do
        float_data "$arqs" "$Numb" && {
            script[$Numb]="$arqs"
            let Numb++
        }
    done
    
    selection=$(selection_fun $Numb)
    [[ -e "${installer}/${script[$selection]}" ]] && {
        ${installer}/${script[$selection]} ${id}
    }
}

tooll
